# -*- coding: utf-8 -*-
"""Untitled

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OeiFTXiiDfORkDoWk9AKkB-uCJ0HNb6w
"""

from google.colab import files
data_to_load=files.upload()

import pandas as pd
import plotly.express as px
df=pd.read_csv("covid_data.csv")
fig=px.scatter(df,x="date",y="cases",color="country")
fig.show()